### ISSUE TITLE
Pushing to a repeat block submits the form

### ISSUE THREAD

**Issue by andrico1234** [stuburger/react-yafl#11]
I'm creating a form that allows user's to add an unlimited number of inputs to the form.

When the user pushes a field to the form, it causes the form to submit. 

The documentation doesn't specify this to be expected behaviour. Is there a way to avoid this from happening? 

Even when the button with type 'submit' doesn't exist on the submit button, it still triggers submit. So I don't think it has anything to do with the submit button's callback firing.

Here's a codesandbox demonstrating this issue

https://codesandbox.io/s/billowing-tdd-6frxc

**Comment by andrico1234** [comment]
One thing to note:

`<form onSubmit={} />` gets called 
`<Form onSubmit={} />` doesn't. 

So one work around would be to change the Submit button to handle the `yafl.submit()` functionality itself. But it still doesn't feel liek the right behaviour

**Comment by stuburger** [comment]
By adding `type="button"` to the button component you were using to push items into the array you can prevent the submit behaviour:) Check it out:  https://codesandbox.io/s/romantic-shape-4e6wz
